target 'Queue' do
  use_frameworks!

  pod 'Alamofire'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['SWIFT_VERSION'] = '3.0'
  end
end