target 'Queue' do
  use_frameworks!

  pod 'Alamofire'
  pod 'Firebase/Database'
  pod 'SnapKit'
  pod 'R.swift'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['SWIFT_VERSION'] = '3.0'
  end
end